// Code generated by ent, DO NOT EDIT.

package proxypool

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the proxypool type in the database.
	Label = "proxy_pool"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldHealthIntervalSeconds holds the string denoting the health_interval_seconds field in the database.
	FieldHealthIntervalSeconds = "health_interval_seconds"
	// FieldFailureThreshold holds the string denoting the failure_threshold field in the database.
	FieldFailureThreshold = "failure_threshold"
	// FieldAutoRebind holds the string denoting the auto_rebind field in the database.
	FieldAutoRebind = "auto_rebind"
	// EdgeProxies holds the string denoting the proxies edge name in mutations.
	EdgeProxies = "proxies"
	// Table holds the table name of the proxypool in the database.
	Table = "proxy_pools"
	// ProxiesTable is the table that holds the proxies relation/edge.
	ProxiesTable = "proxies"
	// ProxiesInverseTable is the table name for the Proxy entity.
	// It exists in this package in order to avoid circular dependency with the "proxy" package.
	ProxiesInverseTable = "proxies"
	// ProxiesColumn is the table column denoting the proxies relation/edge.
	ProxiesColumn = "pool_id"
)

// Columns holds all SQL columns for proxypool fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldName,
	FieldDescription,
	FieldStatus,
	FieldHealthIntervalSeconds,
	FieldFailureThreshold,
	FieldAutoRebind,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/Wei-Shaw/sub2api/ent/runtime"
var (
	Hooks        [1]ent.Hook
	Interceptors [1]ent.Interceptor
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultHealthIntervalSeconds holds the default value on creation for the "health_interval_seconds" field.
	DefaultHealthIntervalSeconds int
	// DefaultFailureThreshold holds the default value on creation for the "failure_threshold" field.
	DefaultFailureThreshold int
	// DefaultAutoRebind holds the default value on creation for the "auto_rebind" field.
	DefaultAutoRebind bool
)

// OrderOption defines the ordering options for the ProxyPool queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByHealthIntervalSeconds orders the results by the health_interval_seconds field.
func ByHealthIntervalSeconds(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHealthIntervalSeconds, opts...).ToFunc()
}

// ByFailureThreshold orders the results by the failure_threshold field.
func ByFailureThreshold(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFailureThreshold, opts...).ToFunc()
}

// ByAutoRebind orders the results by the auto_rebind field.
func ByAutoRebind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAutoRebind, opts...).ToFunc()
}

// ByProxiesCount orders the results by proxies count.
func ByProxiesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newProxiesStep(), opts...)
	}
}

// ByProxies orders the results by proxies terms.
func ByProxies(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProxiesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newProxiesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProxiesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, ProxiesTable, ProxiesColumn),
	)
}
