// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/proxy"
	"github.com/Wei-Shaw/sub2api/ent/proxypool"
)

// ProxyPoolUpdate is the builder for updating ProxyPool entities.
type ProxyPoolUpdate struct {
	config
	hooks    []Hook
	mutation *ProxyPoolMutation
}

// Where appends a list predicates to the ProxyPoolUpdate builder.
func (_u *ProxyPoolUpdate) Where(ps ...predicate.ProxyPool) *ProxyPoolUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProxyPoolUpdate) SetUpdatedAt(v time.Time) *ProxyPoolUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ProxyPoolUpdate) SetDeletedAt(v time.Time) *ProxyPoolUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ProxyPoolUpdate) SetNillableDeletedAt(v *time.Time) *ProxyPoolUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ProxyPoolUpdate) ClearDeletedAt() *ProxyPoolUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *ProxyPoolUpdate) SetName(v string) *ProxyPoolUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ProxyPoolUpdate) SetNillableName(v *string) *ProxyPoolUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ProxyPoolUpdate) SetDescription(v string) *ProxyPoolUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ProxyPoolUpdate) SetNillableDescription(v *string) *ProxyPoolUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ProxyPoolUpdate) ClearDescription() *ProxyPoolUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ProxyPoolUpdate) SetStatus(v string) *ProxyPoolUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ProxyPoolUpdate) SetNillableStatus(v *string) *ProxyPoolUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetHealthIntervalSeconds sets the "health_interval_seconds" field.
func (_u *ProxyPoolUpdate) SetHealthIntervalSeconds(v int) *ProxyPoolUpdate {
	_u.mutation.ResetHealthIntervalSeconds()
	_u.mutation.SetHealthIntervalSeconds(v)
	return _u
}

// SetNillableHealthIntervalSeconds sets the "health_interval_seconds" field if the given value is not nil.
func (_u *ProxyPoolUpdate) SetNillableHealthIntervalSeconds(v *int) *ProxyPoolUpdate {
	if v != nil {
		_u.SetHealthIntervalSeconds(*v)
	}
	return _u
}

// AddHealthIntervalSeconds adds value to the "health_interval_seconds" field.
func (_u *ProxyPoolUpdate) AddHealthIntervalSeconds(v int) *ProxyPoolUpdate {
	_u.mutation.AddHealthIntervalSeconds(v)
	return _u
}

// SetFailureThreshold sets the "failure_threshold" field.
func (_u *ProxyPoolUpdate) SetFailureThreshold(v int) *ProxyPoolUpdate {
	_u.mutation.ResetFailureThreshold()
	_u.mutation.SetFailureThreshold(v)
	return _u
}

// SetNillableFailureThreshold sets the "failure_threshold" field if the given value is not nil.
func (_u *ProxyPoolUpdate) SetNillableFailureThreshold(v *int) *ProxyPoolUpdate {
	if v != nil {
		_u.SetFailureThreshold(*v)
	}
	return _u
}

// AddFailureThreshold adds value to the "failure_threshold" field.
func (_u *ProxyPoolUpdate) AddFailureThreshold(v int) *ProxyPoolUpdate {
	_u.mutation.AddFailureThreshold(v)
	return _u
}

// SetAutoRebind sets the "auto_rebind" field.
func (_u *ProxyPoolUpdate) SetAutoRebind(v bool) *ProxyPoolUpdate {
	_u.mutation.SetAutoRebind(v)
	return _u
}

// SetNillableAutoRebind sets the "auto_rebind" field if the given value is not nil.
func (_u *ProxyPoolUpdate) SetNillableAutoRebind(v *bool) *ProxyPoolUpdate {
	if v != nil {
		_u.SetAutoRebind(*v)
	}
	return _u
}

// AddProxyIDs adds the "proxies" edge to the Proxy entity by IDs.
func (_u *ProxyPoolUpdate) AddProxyIDs(ids ...int64) *ProxyPoolUpdate {
	_u.mutation.AddProxyIDs(ids...)
	return _u
}

// AddProxies adds the "proxies" edges to the Proxy entity.
func (_u *ProxyPoolUpdate) AddProxies(v ...*Proxy) *ProxyPoolUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddProxyIDs(ids...)
}

// Mutation returns the ProxyPoolMutation object of the builder.
func (_u *ProxyPoolUpdate) Mutation() *ProxyPoolMutation {
	return _u.mutation
}

// ClearProxies clears all "proxies" edges to the Proxy entity.
func (_u *ProxyPoolUpdate) ClearProxies() *ProxyPoolUpdate {
	_u.mutation.ClearProxies()
	return _u
}

// RemoveProxyIDs removes the "proxies" edge to Proxy entities by IDs.
func (_u *ProxyPoolUpdate) RemoveProxyIDs(ids ...int64) *ProxyPoolUpdate {
	_u.mutation.RemoveProxyIDs(ids...)
	return _u
}

// RemoveProxies removes "proxies" edges to Proxy entities.
func (_u *ProxyPoolUpdate) RemoveProxies(v ...*Proxy) *ProxyPoolUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveProxyIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProxyPoolUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProxyPoolUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProxyPoolUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProxyPoolUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProxyPoolUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if proxypool.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized proxypool.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := proxypool.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProxyPoolUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := proxypool.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ProxyPool.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := proxypool.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ProxyPool.status": %w`, err)}
		}
	}
	return nil
}

func (_u *ProxyPoolUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(proxypool.Table, proxypool.Columns, sqlgraph.NewFieldSpec(proxypool.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(proxypool.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(proxypool.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(proxypool.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(proxypool.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(proxypool.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(proxypool.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(proxypool.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.HealthIntervalSeconds(); ok {
		_spec.SetField(proxypool.FieldHealthIntervalSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHealthIntervalSeconds(); ok {
		_spec.AddField(proxypool.FieldHealthIntervalSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FailureThreshold(); ok {
		_spec.SetField(proxypool.FieldFailureThreshold, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFailureThreshold(); ok {
		_spec.AddField(proxypool.FieldFailureThreshold, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AutoRebind(); ok {
		_spec.SetField(proxypool.FieldAutoRebind, field.TypeBool, value)
	}
	if _u.mutation.ProxiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   proxypool.ProxiesTable,
			Columns: []string{proxypool.ProxiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedProxiesIDs(); len(nodes) > 0 && !_u.mutation.ProxiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   proxypool.ProxiesTable,
			Columns: []string{proxypool.ProxiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProxiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   proxypool.ProxiesTable,
			Columns: []string{proxypool.ProxiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{proxypool.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProxyPoolUpdateOne is the builder for updating a single ProxyPool entity.
type ProxyPoolUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProxyPoolMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProxyPoolUpdateOne) SetUpdatedAt(v time.Time) *ProxyPoolUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ProxyPoolUpdateOne) SetDeletedAt(v time.Time) *ProxyPoolUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ProxyPoolUpdateOne) SetNillableDeletedAt(v *time.Time) *ProxyPoolUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ProxyPoolUpdateOne) ClearDeletedAt() *ProxyPoolUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *ProxyPoolUpdateOne) SetName(v string) *ProxyPoolUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ProxyPoolUpdateOne) SetNillableName(v *string) *ProxyPoolUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ProxyPoolUpdateOne) SetDescription(v string) *ProxyPoolUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ProxyPoolUpdateOne) SetNillableDescription(v *string) *ProxyPoolUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ProxyPoolUpdateOne) ClearDescription() *ProxyPoolUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ProxyPoolUpdateOne) SetStatus(v string) *ProxyPoolUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ProxyPoolUpdateOne) SetNillableStatus(v *string) *ProxyPoolUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetHealthIntervalSeconds sets the "health_interval_seconds" field.
func (_u *ProxyPoolUpdateOne) SetHealthIntervalSeconds(v int) *ProxyPoolUpdateOne {
	_u.mutation.ResetHealthIntervalSeconds()
	_u.mutation.SetHealthIntervalSeconds(v)
	return _u
}

// SetNillableHealthIntervalSeconds sets the "health_interval_seconds" field if the given value is not nil.
func (_u *ProxyPoolUpdateOne) SetNillableHealthIntervalSeconds(v *int) *ProxyPoolUpdateOne {
	if v != nil {
		_u.SetHealthIntervalSeconds(*v)
	}
	return _u
}

// AddHealthIntervalSeconds adds value to the "health_interval_seconds" field.
func (_u *ProxyPoolUpdateOne) AddHealthIntervalSeconds(v int) *ProxyPoolUpdateOne {
	_u.mutation.AddHealthIntervalSeconds(v)
	return _u
}

// SetFailureThreshold sets the "failure_threshold" field.
func (_u *ProxyPoolUpdateOne) SetFailureThreshold(v int) *ProxyPoolUpdateOne {
	_u.mutation.ResetFailureThreshold()
	_u.mutation.SetFailureThreshold(v)
	return _u
}

// SetNillableFailureThreshold sets the "failure_threshold" field if the given value is not nil.
func (_u *ProxyPoolUpdateOne) SetNillableFailureThreshold(v *int) *ProxyPoolUpdateOne {
	if v != nil {
		_u.SetFailureThreshold(*v)
	}
	return _u
}

// AddFailureThreshold adds value to the "failure_threshold" field.
func (_u *ProxyPoolUpdateOne) AddFailureThreshold(v int) *ProxyPoolUpdateOne {
	_u.mutation.AddFailureThreshold(v)
	return _u
}

// SetAutoRebind sets the "auto_rebind" field.
func (_u *ProxyPoolUpdateOne) SetAutoRebind(v bool) *ProxyPoolUpdateOne {
	_u.mutation.SetAutoRebind(v)
	return _u
}

// SetNillableAutoRebind sets the "auto_rebind" field if the given value is not nil.
func (_u *ProxyPoolUpdateOne) SetNillableAutoRebind(v *bool) *ProxyPoolUpdateOne {
	if v != nil {
		_u.SetAutoRebind(*v)
	}
	return _u
}

// AddProxyIDs adds the "proxies" edge to the Proxy entity by IDs.
func (_u *ProxyPoolUpdateOne) AddProxyIDs(ids ...int64) *ProxyPoolUpdateOne {
	_u.mutation.AddProxyIDs(ids...)
	return _u
}

// AddProxies adds the "proxies" edges to the Proxy entity.
func (_u *ProxyPoolUpdateOne) AddProxies(v ...*Proxy) *ProxyPoolUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddProxyIDs(ids...)
}

// Mutation returns the ProxyPoolMutation object of the builder.
func (_u *ProxyPoolUpdateOne) Mutation() *ProxyPoolMutation {
	return _u.mutation
}

// ClearProxies clears all "proxies" edges to the Proxy entity.
func (_u *ProxyPoolUpdateOne) ClearProxies() *ProxyPoolUpdateOne {
	_u.mutation.ClearProxies()
	return _u
}

// RemoveProxyIDs removes the "proxies" edge to Proxy entities by IDs.
func (_u *ProxyPoolUpdateOne) RemoveProxyIDs(ids ...int64) *ProxyPoolUpdateOne {
	_u.mutation.RemoveProxyIDs(ids...)
	return _u
}

// RemoveProxies removes "proxies" edges to Proxy entities.
func (_u *ProxyPoolUpdateOne) RemoveProxies(v ...*Proxy) *ProxyPoolUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveProxyIDs(ids...)
}

// Where appends a list predicates to the ProxyPoolUpdate builder.
func (_u *ProxyPoolUpdateOne) Where(ps ...predicate.ProxyPool) *ProxyPoolUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProxyPoolUpdateOne) Select(field string, fields ...string) *ProxyPoolUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ProxyPool entity.
func (_u *ProxyPoolUpdateOne) Save(ctx context.Context) (*ProxyPool, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProxyPoolUpdateOne) SaveX(ctx context.Context) *ProxyPool {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProxyPoolUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProxyPoolUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProxyPoolUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if proxypool.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized proxypool.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := proxypool.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProxyPoolUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := proxypool.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ProxyPool.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := proxypool.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ProxyPool.status": %w`, err)}
		}
	}
	return nil
}

func (_u *ProxyPoolUpdateOne) sqlSave(ctx context.Context) (_node *ProxyPool, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(proxypool.Table, proxypool.Columns, sqlgraph.NewFieldSpec(proxypool.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProxyPool.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, proxypool.FieldID)
		for _, f := range fields {
			if !proxypool.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != proxypool.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(proxypool.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(proxypool.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(proxypool.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(proxypool.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(proxypool.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(proxypool.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(proxypool.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.HealthIntervalSeconds(); ok {
		_spec.SetField(proxypool.FieldHealthIntervalSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHealthIntervalSeconds(); ok {
		_spec.AddField(proxypool.FieldHealthIntervalSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FailureThreshold(); ok {
		_spec.SetField(proxypool.FieldFailureThreshold, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFailureThreshold(); ok {
		_spec.AddField(proxypool.FieldFailureThreshold, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AutoRebind(); ok {
		_spec.SetField(proxypool.FieldAutoRebind, field.TypeBool, value)
	}
	if _u.mutation.ProxiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   proxypool.ProxiesTable,
			Columns: []string{proxypool.ProxiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedProxiesIDs(); len(nodes) > 0 && !_u.mutation.ProxiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   proxypool.ProxiesTable,
			Columns: []string{proxypool.ProxiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProxiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   proxypool.ProxiesTable,
			Columns: []string{proxypool.ProxiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ProxyPool{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{proxypool.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
